apiVersion: v1
kind: Service
metadata:
  name: udagram-feed-api
  labels:
    service: udagram-feed-api
spec:
  selector:
    service: udagram-feed-api
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
